SERVICE_CONTAINER_CLS = 'SERVICE_CONTAINER_CLS'
AMQP_URL_CONFIG_KEY = 'AMQP_URI'

RPC_EXCHANGE_CONFIG_KEY = 'rpc_exchange'
RPC_CONNECTION_MAX_SIZE = 'max_size'

SERIALIZER_CONFIG_KEY = 'serializer'
DEFAULT_SERIALIZER = 'pickle'

HEADER_PREFIX = "mia"

